### ISSUE TITLE
Add Danger screenshot

### ISSUE THREAD

**Issue by lfarah** [orta/danger-junit#1]
I'd be cool to add a screenshot illustrating the beauty of **danger-junit**. Something like this:
<img width="706" alt="screen shot 2016-07-30 at 12 40 08 pm" src="https://cloud.githubusercontent.com/assets/6511079/17271466/e56449a4-5652-11e6-8881-6b8b38c7e13f.png">

**Comment by orta** [comment]
Thanks - README is now vastly improved. 👍
