### ISSUE TITLE
You used `puts` in your Dangerfile. To print out text to GitHub use `message` instead

### ISSUE THREAD

**Issue by anthonymonori** [orta/danger-junit#16]
I'm trying to run danger-junit as one of the steps in my CI setup. This is the contents of my `danger/UnitTestDangerfile`:
```
junit.parse "app/build/outputs/junit/merged-test-results.xml"
junit.show_skipped_tests = true
junit.report
```

But I get the complaint that I am using puts instead of message which is confusing for couple of reasons:
(1) I could not find any `puts` command in this plugin
(2) That error message assumes I am running on GitHub

This is the raw output from my CI server:
```
[15:17:14]: $ bundle exec danger --danger_id=unit-tests --dangerfile=danger/UnitTestDangerfile --new-comment
[15:17:15]: ▸ You used `puts` in your Dangerfile. To print out text to GitHub use `message` instead
```

Regarding (2) - although I can see from the code it should support GitLab too and there are else-clauses if we are running in an environment other than GitHub.

What can be wrong?

**Comment by orta** [comment]
Maybe a dependency is using `puts`?

**Comment by anthonymonori** [comment]
Well, there's two runtime dependencies on danger-junit, one of them is obviously danger, the other one is ox. After a quick look, I can surely tell that `ox` __is using__ `puts`.

Is this just happening to me or everybody using `danger-junit`? Do we have any utilisation stats?

**Comment by orta** [comment]
Looks like 91k download: https://rubygems.org/gems/danger-junit

I think people use don't mind about the puts warning.

**Comment by anthonymonori** [comment]
True and forgot about rubygems 😬 

I also originally submitted this because I confused it with an error, which was something else, so now I can see why nobody else complained about it. 

---

I still don't quite get the purpose of that warning (the part about it not being okay to print with `puts` if you are running in GitHub - which I am not)

**Comment by orta** [comment]
The feature is probably from when Danger just supported GitHub, if you want, you can go and improve it in danger by making it say the correct platform?
