### ISSUE TITLE
Customize fail message

### ISSUE THREAD

**Issue by pjechris** [orta/danger-junit#17]
It would be nice if we could customize failure message.
For example I'd like to show number of succeeded/failed tests.

**Comment by orta** [comment]
Why customize it? Sounds like a better feature for the lib, send a PR?

**Comment by aiKrice** [comment]
I think it could be solved by using the exposed `attr_accessor :passes`, for exemple:

Dangerfile: 


```ruby
...
junit.report
if junit.passes.count > 0:
    message "${junit.passes.count} tests succeeds"
end
```

If ok @pjechris , this issue could be closed

**Comment by pjechris** [comment]
I don't remember what I planned to achieve with this, it was two years ago 😆 
But I guess your solution would do it @SaezChristopher :)
