### ISSUE TITLE
Do you have any plan to publish v1.0 to RubyGems?

### ISSUE THREAD

**Issue by jmatsu** [orta/danger-junit#20]
Hi, thank you for providing the useful library!

We would like to handle multiple result files and found the usage in the current master. However, it seems v1.0 hasn't been released yet.

https://rubygems.org/gems/danger-junit

Is there any concern to block the release? Thanks.

**Comment by jmatsu** [comment]
BTW, i'm currently using `gem 'danger-junit', git: 'https://github.com/orta/danger-junit', ref: '32fc5d2c026604a0880a3901783628dab06e4877'` for now.

**Comment by orta** [comment]
Shipped - thanks!
