### ISSUE TITLE
Invalid `Dangerfile` file: undefined method `nodes'

### ISSUE THREAD

**Issue by Vacxe** [orta/danger-junit#25]
My Danger file include this lines
```
junit_tests_dir = "**/build/**/reports/jacoco/report.xml"
Dir[junit_tests_dir].each do |file_name|
    junit.parse file_name
    junit.report
end
```

I have exception
```
[!] Invalid `Dangerfile` file: undefined method `nodes' for #<Ox::DocType:0x000055b4b0207848>
#  from Dangerfile:14
#  -------------------------------------------
#  Dir[junit_tests_dir].each do |file_name|
>      junit.parse file_name
#      junit.report 
#  -------------------------------------------

```

Do you have any ideas?

Also, XML file is really large. ~30Mb

**Comment by Vacxe** [comment]
@orta anybody here?

**Comment by aiKrice** [comment]
I think you should give more information: for example if you can the file, also the stack trace just after the crash to indentify your ruby stack

**Comment by lm2s** [comment]
@Vacxe This has happened to me when the results XML file was empty or not valid.

**Comment by orta** [comment]
Can't hurt to add some extra checks that the file exists and is valid and provide some useful error emssages

**Comment by Vacxe** [comment]
@lm2s @orta guys, the issue has been created about 1 year ago. Now I can't provide any messages or ect.
